.
sergey-berezin/402_yarkova pull request #2
Opened 2023-10-26 21:42 UTC by Yulie00

2023-10-27 07:12 UTC, sergey-berezin requested changes
В PR нет проекта с консольным приложением. Нужно добавить.

2023-10-27 07:12 UTC, sergey-berezin commented on Class1.cs
> +                Console.WriteLine(sentence);
Компонент не должен использовать консольный ввод/вывод. Во втором задании компонент будет использоваться в графическом приложении без консоли.

2023-10-27 07:12 UTC, sergey-berezin commented on Class1.cs
> +                    Console.WriteLine("Вы ввели пустую строку. На этом всё.");
Компонент не может использовать консольный вывод.

2023-10-27 07:12 UTC, sergey-berezin commented on Class1.cs
> +                var modelPath = "C:\\Users\\Admin\\source\\repos\\ConsoleApp_Lab_1\\ConsoleApp_Lab_1\\bert-large-uncased-whole-word-masking-finetuned-squad.onnx";
Что будет, если у меня на компьютере нет пользователя "Admin"?

2023-10-27 07:12 UTC, sergey-berezin commented on Class1.cs
> +                                    Console.WriteLine($"Загружено: {percentage:F2}%");
Консольный вывод не будет виден во втором задании.

2023-10-28 11:32 UTC, Yulie00 commented
Я добавила консольное приложение

2023-10-31 08:25 UTC, sergey-berezin commented
Сейчас в PR всего только консольное приложение. Нужен ещё проект и исходные файлы для компонента.

2023-10-31 09:31 UTC, Yulie00 commented
Я добавила файлы

2023-10-31 12:39 UTC, sergey-berezin requested changes
Нужно сохранить структуру директорий. Сейчас .sln не открывается, т.к. не может найти проекты. Кроме того, два проекта (csproj) в одной папке находиться не могут.

2023-10-31 14:03 UTC, Yulie00 commented
Так? bin и obj ведь не нужно добавлять?

2023-10-31 16:41 UTC, sergey-berezin requested changes

2023-10-31 16:41 UTC, sergey-berezin commented on NugPack/123
Лишний файл.

2023-10-31 16:41 UTC, sergey-berezin commented on NugPack/Class1.cs
> +            //var hobbit = " ";
Закомментированный код нужно убрать.

2023-10-31 18:08 UTC, Yulie00 commented
Исправила

2023-11-07 07:42 UTC, sergey-berezin commented on Nugpack/Class1.cs
> +                var modelPath = "C:\\Users\\Admin\\source\\repos\\ConsoleApp_Lab_1\\ConsoleApp_Lab_1\\bert-large-uncased-whole-word-masking-finetuned-squad.onnx";
Не будет работать, если пользователь на другой машине называется не Admin.

2023-11-07 07:43 UTC, sergey-berezin commented on Nugpack/Class1.cs
> +        public static IEnumerable<string> Answer_Generate(string inputText, params string[] inputQuestions)
Этот метод не асинхронный. Асинхронность требуется в задании 1.

2023-11-07 07:44 UTC, sergey-berezin commented
PR принимаю. Обратите внимание на комментарии. К ним в любом случае придётся вернуться во втором задании.

2023-11-07 07:44 UTC, merged